---
title: "Savannah Work"
author: "Savannah Flanagan"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(tidyverse)
library(gtsummary)
library(emulator)
```

```{r}
test_df=read_csv('Project_1_data.csv') %>% janitor::clean_names() 

test_df=test_df %>%  
  mutate(is_first_child=case_when(
    is.na(is_first_child) &nr_siblings==0 ~ 'yes',
    TRUE ~is_first_child
  )) %>% 
        mutate(gender=as.factor(gender),
               ethnic_group=as.factor(ethnic_group),
               parent_educ=as.factor(parent_educ),
               lunch_type=as.factor(lunch_type),
               test_prep=as.factor(test_prep),
               parent_marital_status=as.factor(parent_marital_status),
               practice_sport=as.factor(practice_sport),
               is_first_child=as.factor(is_first_child),
               transport_means=as.factor(transport_means),
               wkly_study_hours=as.factor(wkly_study_hours)) %>% drop_na()
 
```

```{r}
summary(test_df)

test_df %>% 
  ggplot(aes(x=math_score))+geom_histogram()
test_df %>% 
  ggplot(aes(x=reading_score))+geom_histogram()
test_df %>% 
  ggplot(aes(x=writing_score))+geom_histogram()
```

```{r}
stu_data=table(test_df$gender,test_df$ethnic_group)

chisq.test(stu_data)
```

```{r}

# Loop through pairs of columns and run the chi-square test

for (i in 1:(11 - 1)) {
  for (j in (i + 1):11) {
    # Get the two columns to test
    col1 <- test_df[[i]]
    col2 <- test_df[[j]]
    
    contingency_table <- table(col1, col2)
    
    # Perform the chi-square test
    chi_test <- chisq.test(contingency_table)
    
    #PRint the results 
    if(chi_test$p.value<.05){
      
      
      cat("Chi-square test for columns", colnames(test_df)[i], "and", colnames(test_df)[j], "\n")
    print(chi_test)
    

    }
    
  }
}

ggplot(test_df, aes(x = nr_siblings, fill = gender)) +
      geom_bar(position = "fill") +
      labs(y = "Proportion", title = "Pairwise Relationship")
ggplot(test_df, aes(x = nr_siblings, fill = is_first_child)) +
      geom_bar(position = "fill") +
      labs(y = "Proportion", title = "Pairwise Relationship")

```

## Writing Score
```{r}

df_4_mdl_write=test_df %>% dplyr::select(gender,ethnic_group,parent_educ,lunch_type,test_prep,parent_marital_status,practice_sport,is_first_child,transport_means,wkly_study_hours,writing_score)
full_fit_write=lm(writing_score ~ .^2,data=df_4_mdl_write)
```

```{r}
summary(full_fit_write)
```

```{r}
stepwise_model_write <- step(full_fit_write, direction = "both", trace = 1)

summary(stepwise_model_write)
```


## MAth Score

```{r}

df_4_mdl_math=test_df %>% dplyr::select(gender,ethnic_group,parent_educ,lunch_type,test_prep,parent_marital_status,practice_sport,is_first_child,transport_means,wkly_study_hours,math_score)
full_fit_math=lm(math_score ~ .^2,data=df_4_mdl_math)
```

```{r}
summary(full_fit_math)
```

```{r}
stepwise_model_math <- step(full_fit_math, direction = "both", trace = 1)

summary(stepwise_model_math)
```


## REading Score 
```{r}

df_4_mdl_read=test_df %>% dplyr::select(gender,ethnic_group,parent_educ,lunch_type,test_prep,parent_marital_status,practice_sport,is_first_child,transport_means,wkly_study_hours,reading_score)
full_fit_read=lm(reading_score ~ .^2,data=df_4_mdl_read)
```

```{r}
summary(full_fit_read)
```

```{r}
stepwise_model_read <- step(full_fit_read, direction = "both", trace = 1)

summary(stepwise_model_read)
```

## Diagnostics 

### Writing
```{r}

plot(stepwise_model_write)


step_as_lm_write=lm(formula = writing_score ~ gender + ethnic_group + parent_educ + 
    lunch_type + test_prep + parent_marital_status + practice_sport + 
    is_first_child + transport_means + wkly_study_hours + ethnic_group:transport_means + 
    lunch_type:practice_sport + lunch_type:wkly_study_hours + 
    parent_marital_status:is_first_child + parent_marital_status:wkly_study_hours, data = df_4_mdl_write)

library('MASS')
boxcox(step_as_lm_write)

step_as_lm_write=lm(formula = (writing_score)^2 ~ gender + ethnic_group + parent_educ + 
    lunch_type + test_prep + parent_marital_status + practice_sport + 
    is_first_child + transport_means + wkly_study_hours + ethnic_group:transport_means + 
    lunch_type:practice_sport + lunch_type:wkly_study_hours + 
    parent_marital_status:is_first_child + parent_marital_status:wkly_study_hours, data = df_4_mdl_write)

plot(step_as_lm_write)


```

```{r}

plot(stepwise_model_math)

step_as_lm_math=lm(formula = math_score ~ gender + ethnic_group + parent_educ + 
    lunch_type + test_prep + parent_marital_status + practice_sport + 
    is_first_child + transport_means + wkly_study_hours + ethnic_group:transport_means + 
    parent_educ:parent_marital_status + parent_educ:is_first_child + 
    lunch_type:practice_sport + lunch_type:transport_means + 
    test_prep:is_first_child + test_prep:wkly_study_hours + parent_marital_status:is_first_child + 
    parent_marital_status:transport_means + parent_marital_status:wkly_study_hours + 
    is_first_child:transport_means + is_first_child:wkly_study_hours,data = df_4_mdl_math)
```

```{r}

plot(stepwise_model_read)

```


##ADD in other scores


## Writing Score2
```{r}

df_4_mdl_write2=test_df %>% dplyr::select(gender,ethnic_group,parent_educ,lunch_type,test_prep,parent_marital_status,practice_sport,is_first_child,transport_means,wkly_study_hours,writing_score,math_score,reading_score)
full_fit_write2=lm(writing_score ~ .^2,data=df_4_mdl_write2)
```

```{r}
summary(full_fit_write2)
```

```{r}
stepwise_model_write2 <- step(full_fit_write2, direction = "both", trace = 1)

summary(stepwise_model_write2)
```


## MAth Score

```{r}

df_4_mdl_math2=test_df %>% dplyr::select(gender,ethnic_group,parent_educ,lunch_type,test_prep,parent_marital_status,practice_sport,is_first_child,transport_means,wkly_study_hours,math_score,writing_score,reading_score)
full_fit_math2=lm(math_score ~ .^2,data=df_4_mdl_math2)
```

```{r}
summary(full_fit_math2)
```

```{r}
stepwise_model_math2 <- step(full_fit_math2, direction = "both", trace = 1)

summary(stepwise_model_math2)
```


## REading Score 
```{r}

df_4_mdl_read2=test_df %>% dplyr::select(gender,ethnic_group,parent_educ,lunch_type,test_prep,parent_marital_status,practice_sport,is_first_child,transport_means,wkly_study_hours,reading_score,writing_score,math_score)
full_fit_read2=lm(reading_score ~ .^2,data=df_4_mdl_read2)
```

```{r}
summary(full_fit_read2)
```

```{r}
stepwise_model_read2 <- step(full_fit_read2, direction = "both", trace = 1)

summary(stepwise_model_read2)
```

